name: Hello Github Actions

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: say hello
        run: echo "Hello World!"
